# Generated by Django 5.1.5 on 2025-01-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=30, unique=True)),
                ('station_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temperature', models.FloatField(null=True)),
                ('min_temperature', models.FloatField(null=True)),
                ('precipitation', models.FloatField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.weatherstation')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_max_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('avg_precipitation', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_statistics', to='weather.weatherstation')),
            ],
        ),
    ]
