# Generated by Django 5.1.5 on 2025-01-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='station_id',
        ),
    ]
