# Generated by Django 5.1.5 on 2025-01-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_weatherstation_station_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherrecord',
            unique_together={('station', 'date')},
        ),
    ]
