# Generated by Django 5.1.5 on 2025-01-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_alter_weatherrecord_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WeatherStatistics",
            new_name="WeatherStatistic",
        ),
        migrations.AlterField(
            model_name="weatherstation",
            name="station_name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
