# Generated by Django 5.1.5 on 2025-01-29 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0007_alter_weatherstatistic_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherstatistic",
            name="station",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_statistics",
                to="weather.weatherstation",
            ),
        ),
    ]
