# Generated by Django 5.1.5 on 2025-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0008_alter_weatherstatistic_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherstatistic",
            name="year",
            field=models.PositiveSmallIntegerField(default=1997),
            preserve_default=False,
        ),
    ]
