# Generated by Django 5.1.5 on 2025-01-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0009_weatherstatistic_year"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherstatistic",
            unique_together={("station", "year")},
        ),
    ]
