# Generated by Django 5.1.5 on 2025-01-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0011_alter_weatherstatistic_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherstatistic",
            name="avg_max_temperature",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weatherstatistic",
            name="avg_min_temperature",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weatherstatistic",
            name="total_precipitation",
            field=models.FloatField(null=True),
        ),
    ]
