apiVersion: apps/v1
kind: Deployment
metadata:
  name: corteva-weather-app
  namespace: corteva
  labels:
    app: corteva-weather-app
# Deployment specification
spec:
  replicas: 3
  # This will select the pods
  selector:
    matchLabels:
      app: corteva-weather-app
  template:
    metadata:
      labels:
        app: corteva-weather-app
    spec:
      containers:
      - name: corteva-weather-app
        image: elysium1436/corteva-weather-app
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: VERY_SECRET_KEY