apiVersion: v1
kind: Service
metadata:
  name: corteva-weather-service
  namespace: corteva
  labels:
    app: corteva-weather-app
spec:
  selector:
    app: corteva-weather-app
  ports:
    - protocol: TCP
      port: 8000
  type: NodePort